# Generated by Django 6.0 on 2025-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=5)),
                ('genre', models.CharField(max_length=15)),
                ('rate', models.FloatField()),
                ('RT', models.IntegerField()),
                ('content', models.TextField()),
                ('Dir', models.CharField(max_length=30)),
                ('MC', models.CharField(max_length=30)),
            ],
        ),
    ]
