# Generated by Django 6.0 on 2025-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='Dir',
            field=models.CharField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='MC',
            field=models.CharField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='RT',
            field=models.CharField(max_length=15),
        ),
    ]
