# Generated by Django 6.0 on 2025-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0002_review_poster_alter_review_dir_alter_review_mc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='RT',
            field=models.IntegerField(),
        ),
    ]
