# Generated by Django 6.0 on 2025-12-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0003_alter_review_rt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('romance', '로맨스'), ('comedy', '코미디'), ('drama', '드라마'), ('fantasy', '판타지'), ('horror', '공포')], max_length=15),
        ),
    ]
