# Generated by Django 6.0 on 2026-01-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='ideas.idea')),
            ],
        ),
    ]
